### ISSUE TITLE
SSH Keys not working

### ISSUE THREAD

**Issue by PascalKu** [Corsinvest/cv4pve-api-java#4]
Hey there,

i am trying to change my ssh keys with the code below inside PVEConfig.
<img width="725" alt="Bildschirmfoto 2020-04-13 um 23 51 36" src="https://user-images.githubusercontent.com/29168749/79164621-b837ce00-7de1-11ea-9e80-5c0f5859a3b4.png">

Now an error occures.

```
java.io.IOException: Server returned HTTP response code: 400 for URL: https://192.168.178.131:8006/api2/json/nodes/pve/qemu/1203/config
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_192]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_192]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_192]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_192]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944) ~[na:1.8.0_192]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939) ~[na:1.8.0_192]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_192]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938) ~[na:1.8.0_192]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508) ~[na:1.8.0_192]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_192]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[na:1.8.0_192]
	at it.corsinvest.proxmoxve.api.PveClientBase.executeAction(PveClientBase.java:355) [main/:na]
	at it.corsinvest.proxmoxve.api.PveClientBase.create(PveClientBase.java:178) [main/:na]
	at it.corsinvest.proxmoxve.api.PveClient$PVENodes$PVEItemNode$PVEQemu$PVEItemVmid$PVEConfig.setRest(PveClient.java:9391) [main/:na]
	at de.vpsnow.restendpoint.service.impl.ProxmoxDeploymentService.lambda$createServer$0(ProxmoxDeploymentService.java:68) [main/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_192]
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://192.168.178.131:8006/api2/json/nodes/pve/qemu/1203/config
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[na:1.8.0_192]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_192]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[na:1.8.0_192]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347) ~[na:1.8.0_192]
	at it.corsinvest.proxmoxve.api.PveClientBase.executeAction(PveClientBase.java:352) [main/:na]
	... 6 common frames omitted
```

**Comment by franklupo** [comment]
Hi,
if usging pvesh inside Proxmox VE node working?

best regards

**Comment by PascalKu** [comment]
yes :)

**Comment by franklupo** [comment]
HI,
try to pass parameter sskeys without URLEncoder.encode.

**Comment by franklupo** [comment]
News?

**Comment by PascalKu** [comment]
no, it's still returning 400: "Parameter verification failed."

**Comment by franklupo** [comment]
Hi,
use URLEncoder.encode.

**Comment by PascalKu** [comment]
no changes...:

400
Parameter verification failed.

keys is a List<String> with ssh Keys like ssh-rsa .... 

```
if (keys != null) {
    final String result = String.join("\n", keys);

    System.out.println(result);

    parameters.put("ciuser", "root");

    try {
        parameters.put("sshkeys", URLEncoder.encode(result, "UTF-8").replace("+", "%20"));
    } catch (UnsupportedEncodingException e) {
        e.printStackTrace();
    }
}
```

postData.toString():

```ipconfig0=ip%3D109.230.235.239%2F25%2Cgw%3D109.230.235.129%2Cip6%3D2a05%3Abec0%3A0030%3A2%3A%3A1%2F48%2Cgw6%3D2a05%3Abec0%3A30%3A%3A1&cores=3&memory=4096&sshkeys=<full-ssh-key>&ciuser=root```

**Comment by franklupo** [comment]
see https://github.com/Corsinvest/cv4pve-api-java/issues/7#issuecomment-684788097

**Comment by PascalKu** [comment]
nope :(

**Comment by PascalKu** [comment]
any ideas?
